### ISSUE TITLE
textadept-curses doesn't build on Ubuntu 22.04

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#294]
I feel I'm starting to be annoying. Maybe it's because I have an easy way to build for a bunch of distros using Docker... sorry...

```
g++ -Os -std=c++17 -pedantic -DSCI_LEXER -DNDEBUG -Iscintilla/include -Iscintilla/src -Ilexilla/include -Ilexilla/lexlib -Wall -DCURSES -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -c scintilla/curses/PlatCurses.cxx -o PlatCurses.o
In file included from scintilla/curses/PlatCurses.cxx:45:
scintilla/src/Document.h:204:47: error: expected class-name before '{' token
  204 | struct RegexError : public std::runtime_error {
      |                                               ^
scintilla/src/Document.h: In constructor 'Scintilla::Internal::RegexError::RegexError()':
scintilla/src/Document.h:205:42: error: expected class-name before '(' token
  205 |         RegexError() : std::runtime_error("regex failure") {}
      |                                          ^
scintilla/src/Document.h:205:42: error: expected '{' before '(' token
```

**Comment by kbarni** [comment]
See this solution, if it helps: https://github.com/orbitalquark/textadept/issues/286

Check if there is `#include <stdexcept>` in `scintilla/src/Document.h`. If it's not there, you need to update your local branch.

**Comment by orbitalquark** [comment]
Not at all. I appreciate the reports. I only build on Ubuntu (both locally and via Docker), so I'm not exposed to different compilers and setups.

Hopefully this is fixed via https://github.com/orbitalquark/scinterm/commit/c62a132ba56782312448c54d0adf506afa439288

**Comment by paaguti** [comment]
Interesting… I’m using docker to isolate… and only for that. Each container exhibits the quirks of its OS, including compiler specifics… this is how I detect all the problems.

Enviado desde mi iPhone
